-- ***********************************************************
-- **                    Hydromancerx                       **
-- ***********************************************************

require "Farming/ScavengeDefinition";

getTexture("Item_HCBeetle.png");
getTexture("Item_HCBollweevil.png");
getTexture("Item_HCLadybug.png");
getTexture("Item_HCDragonfly.png");
getTexture("Item_HCGardenspider.png");
getTexture("Item_HCCaterpillar.png");
getTexture("Item_HCCaterpillar2.png");
getTexture("Item_HCBumblebee.png");
getTexture("Item_HCHoneybee.png");
getTexture("Item_HCBeehive.png");
getTexture("Item_HCBeetlegrub.png");
getTexture("Item_HCCicada.png");
getTexture("Item_HCRedant.png");
getTexture("Item_HCBlackant.png");
getTexture("Item_HCPillbug.png");
getTexture("Item_HCFirefly.png");
getTexture("Item_HCTermite.png");
getTexture("Item_HCYellowjacket.png");
getTexture("Item_HCButterfly.png");
getTexture("Item_HCMonarch.png");
getTexture("Item_HCMolecricket.png");
getTexture("Item_HCBlackwidow.png");
getTexture("Item_HCHousespider.png");
getTexture("Item_HCChrysalis.png");
getTexture("Item_HCChrysalis2.png");
getTexture("Item_HCHousefly.png");
getTexture("Item_HCSilkmothmale.png");
getTexture("Item_HCSilkmothfemale.png");
getTexture("Item_HCSnail.png");
getTexture("Item_HCSlug.png");

-- bugs
local HCBeetle = {};
HCBeetle.type = "Hydrocraft.HCBeetle";
HCBeetle.minCount = 1;
HCBeetle.maxCount = 2;
HCBeetle.skill = 3;
local HCBollweevil = {};
HCBollweevil.type = "Hydrocraft.HCBollweevil";
HCBollweevil.minCount = 1;
HCBollweevil.maxCount = 2;
HCBollweevil.skill = 7;
local HCLadybug = {};
HCLadybug.type = "Hydrocraft.HCLadybug";
HCLadybug.minCount = 1;
HCLadybug.maxCount = 2;
HCLadybug.skill = 2;
local HCDragonfly = {};
HCDragonfly.type = "Hydrocraft.HCDragonfly";
HCDragonfly.minCount = 1;
HCDragonfly.maxCount = 2;
HCDragonfly.skill = 9;
local HCGardenspider = {};
HCGardenspider.type = "Hydrocraft.HCGardenspider";
HCGardenspider.minCount = 1;
HCGardenspider.maxCount = 2;
HCGardenspider.skill = 3;
local HCCaterpillar = {};
HCCaterpillar.type = "Hydrocraft.HCCaterpillar";
HCCaterpillar.minCount = 1;
HCCaterpillar.maxCount = 2;
HCCaterpillar.skill = 6;
local HCCaterpillar2 = {};
HCCaterpillar2.type = "Hydrocraft.HCCaterpillar2";
HCCaterpillar2.minCount = 1;
HCCaterpillar2.maxCount = 2;
HCCaterpillar2.skill = 6;
local HCBumblebee = {};
HCBumblebee.type = "Hydrocraft.HCBumblebee";
HCBumblebee.minCount = 1;
HCBumblebee.maxCount = 2;
HCBumblebee.skill = 7;
local HCHoneybee = {};
HCHoneybee.type = "Hydrocraft.HCHoneybee";
HCHoneybee.minCount = 1;
HCHoneybee.maxCount = 2;
HCHoneybee.skill = 7;
local HCBeehive = {};
HCBeehive.type = "Hydrocraft.HCBeehive";
HCBeehive.minCount = 1;
HCBeehive.maxCount = 1;
HCBeehive.skill = 10;
local HCBeetlegrub = {};
HCBeetlegrub.type = "Hydrocraft.HCBeetlegrub";
HCBeetlegrub.minCount = 1;
HCBeetlegrub.maxCount = 2;
HCBeetlegrub.skill = 2;
local HCCicada = {};
HCCicada.type = "Hydrocraft.HCCicada";
HCCicada.minCount = 1;
HCCicada.maxCount = 2;
HCCicada.skill = 4;
local HCRedant = {};
HCRedant.type = "Hydrocraft.HCRedant";
HCRedant.minCount = 1;
HCRedant.maxCount = 2;
HCRedant.skill = 1;
local HCBlackant = {};
HCBlackant.type = "Hydrocraft.HCBlackant";
HCBlackant.minCount = 1;
HCBlackant.maxCount = 2;
HCBlackant.skill = 0;
local HCPillbug = {};
HCPillbug.type = "Hydrocraft.HCPillbug";
HCPillbug.minCount = 1;
HCPillbug.maxCount = 2;
HCPillbug.skill = 0;
local HCFirefly = {};
HCFirefly.type = "Hydrocraft.HCFirefly";
HCFirefly.minCount = 1;
HCFirefly.maxCount = 2;
HCFirefly.skill = 9;
local HCTermite = {};
HCTermite.type = "Hydrocraft.HCTermite";
HCTermite.minCount = 1;
HCTermite.maxCount = 2;
HCTermite.skill = 5;
local HCYellowjacket = {};
HCYellowjacket.type = "Hydrocraft.HCYellowjacket";
HCYellowjacket.minCount = 1;
HCYellowjacket.maxCount = 2;
HCYellowjacket.skill = 8;
local HCButterfly = {};
HCButterfly.type = "Hydrocraft.HCButterfly";
HCButterfly.minCount = 1;
HCButterfly.maxCount = 2;
HCButterfly.skill = 3;
local HCMonarch = {};
HCMonarch.type = "Hydrocraft.HCMonarch";
HCMonarch.minCount = 1;
HCMonarch.maxCount = 2;
HCMonarch.skill = 3;
local HCMolecricket = {};
HCMolecricket.type = "Hydrocraft.HCMolecricket";
HCMolecricket.minCount = 1;
HCMolecricket.maxCount = 2;
HCMolecricket.skill = 4;
local HCBlackwidow = {};
HCBlackwidow.type = "Hydrocraft.HCBlackwidow";
HCBlackwidow.minCount = 1;
HCBlackwidow.maxCount = 2;
HCBlackwidow.skill = 7;
local HCHousespider = {};
HCHousespider.type = "Hydrocraft.HCHousespider";
HCHousespider.minCount = 1;
HCHousespider.maxCount = 2;
HCHousespider.skill = 5;
local HCChrysalis = {};
HCChrysalis.type = "Hydrocraft.HCChrysalis";
HCChrysalis.minCount = 1;
HCChrysalis.maxCount = 2;
HCChrysalis.skill = 3;
local HCChrysalis2 = {};
HCChrysalis2.type = "Hydrocraft.HCChrysalis2";
HCChrysalis2.minCount = 1;
HCChrysalis2.maxCount = 2;
HCChrysalis2.skill = 3;
local HCHousefly = {};
HCHousefly.type = "Hydrocraft.HCHousefly";
HCHousefly.minCount = 1;
HCHousefly.maxCount = 2;
HCHousefly.skill = 6;
local HCSilkmothmale = {};
HCSilkmothmale.type = "Hydrocraft.HCSilkmothmale";
HCSilkmothmale.minCount = 1;
HCSilkmothmale.maxCount = 1;
HCSilkmothmale.skill = 10;
local HCSilkmothfemale = {};
HCSilkmothfemale.type = "Hydrocraft.HCSilkmothfemale";
HCSilkmothfemale.minCount = 1;
HCSilkmothfemale.maxCount = 1;
HCSilkmothfemale.skill = 10;
local HCSnail = {};
HCSnail.type = "Hydrocraft.HCSnail";
HCSnail.minCount = 1;
HCSnail.maxCount = 2;
HCSnail.skill = 1;
local HCSlug = {};
HCSlug.type = "Hydrocraft.HCSlug";
HCSlug.minCount = 1;
HCSlug.maxCount = 2;
HCSlug.skill = 1;

table.insert(scavenges.insects, HCBeetle);
table.insert(scavenges.insects, HCBollweevil);
table.insert(scavenges.insects, HCLadybug);
table.insert(scavenges.insects, HCDragonfly);
table.insert(scavenges.insects, HCGardenspider);
table.insert(scavenges.insects, HCCaterpillar);
table.insert(scavenges.insects, HCCaterpillar2);
table.insert(scavenges.insects, HCBumblebee);
table.insert(scavenges.insects, HCHoneybee);
table.insert(scavenges.insects, HCBeehive);
table.insert(scavenges.insects, HCBeetlegrub);
table.insert(scavenges.insects, HCCicada);
table.insert(scavenges.insects, HCRedant);
table.insert(scavenges.insects, HCBlackant);
table.insert(scavenges.insects, HCPillbug);
table.insert(scavenges.insects, HCFirefly);
table.insert(scavenges.insects, HCTermite);
table.insert(scavenges.insects, HCYellowjacket);
table.insert(scavenges.insects, HCButterfly);
table.insert(scavenges.insects, HCMonarch);
table.insert(scavenges.insects, HCMolecricket);
table.insert(scavenges.insects, HCBlackwidow);
table.insert(scavenges.insects, HCHousespider);
table.insert(scavenges.insects, HCChrysalis);
table.insert(scavenges.insects, HCChrysalis2);
table.insert(scavenges.insects, HCHousefly);
table.insert(scavenges.insects, HCSilkmothmale);
table.insert(scavenges.insects, HCSilkmothfemale);
table.insert(scavenges.insects, HCSnail);
table.insert(scavenges.insects, HCSlug);
