-- ***********************************************************
-- **                    Hydromancerx                       **
-- ***********************************************************

require "Farming/ScavengeDefinition";

getTexture("Item_HCCandleberry.png");
getTexture("Item_HCHuckleberry.png");
getTexture("Item_HCCranberry.png");
getTexture("Item_HCSeaberry.png");
getTexture("Item_HCBlackcurrant.png");
getTexture("Item_HCRedcurrant.png");
getTexture("Item_HCArrowwoodberry.png");
getTexture("Item_HCRaspberry.png");
getTexture("Item_HCElderberry.png");
getTexture("Item_HCHolly.png");
getTexture("Item_HCBlackthornberry.png");
getTexture("Item_HCCrampbarkberry.png");
getTexture("Item_HCCrowberry.png");
getTexture("Item_HCGooseberry.png");
getTexture("Item_HCHawthornfruit.png");
getTexture("Item_HCJuniperberry.png");
getTexture("Item_HCSumacberry.png");
getTexture("Item_HCGrass.png");
getTexture("Item_HCReeds.png");
getTexture("Item_HCFlax.png");
getTexture("Item_HCMilkweedroot.png");
getTexture("Item_HCClover.png");
getTexture("Item_HCNettles.png");
getTexture("Item_HCThistle.png");
getTexture("Item_HCJutestems.png");
getTexture("Item_HCRosebud.png");
getTexture("Item_HCSunflower.png");
getTexture("Item_HCVenusflytrap.png");
getTexture("Item_HCCamomile.png");
getTexture("Item_HCLavender.png");
getTexture("Item_HCFlaxflower.png");
getTexture("Item_HCDaisy.png");
getTexture("Item_HCIris.png");
getTexture("Item_HCSkullcap.png");
getTexture("Item_HCBluebell.png");
getTexture("Item_HCStraw.png");
getTexture("Item_HCBark.png");
getTexture("Item_HCBirchbark.png");
getTexture("Item_HCWillowbark.png");
getTexture("Item_HCFircone.png");
getTexture("Item_HCAcorn.png");
getTexture("Item_HCBirchcatkin.png");
getTexture("Item_HCBeechnut.png");
getTexture("Item_HCChestnut.png");
getTexture("Item_HCHickorynuts.png");
getTexture("Item_HCHickoryleaves.png");
getTexture("Item_HCOakleaves.png");
getTexture("Item_HCMapleleaf.png");
getTexture("Item_HCFern.png");
getTexture("Item_HCFiddleheadfern.png");
getTexture("Item_HCWillowbranch.png");
getTexture("Item_HCAlderbough.png");
getTexture("Item_HCElmbough.png");
getTexture("Item_HCSprucebough.png");
getTexture("Item_HCYewbough.png");
getTexture("Item_HCPinebough.png");
getTexture("Item_HCFirbough.png");
getTexture("Item_Cabbage.png");
getTexture("Item_Grapes.png");
getTexture("Item_Lemon.png");
getTexture("Item_Orange.png");
getTexture("Item_Potato.png");
getTexture("Item_RedRadish.png");
getTexture("Item_Tomato.png");
getTexture("Item_HCMulberryleaf.png");
getTexture("Item_HCMulberry.png");
getTexture("Item_HCBlewitshroom.png");
getTexture("Item_HCLobstershroom.png");
getTexture("Item_HCWitchshatshroom.png");
getTexture("Item_HCYellowmorelshroom.png");
getTexture("Item_HCChantrelle.png");

-- Plants
local HCCandleberry = {};
HCCandleberry.type = "Hydrocraft.HCCandleberry";
HCCandleberry.minCount = 2;
HCCandleberry.maxCount = 5;
HCCandleberry.skill = 3;
local HCHuckleberry = {};
HCHuckleberry.type = "Hydrocraft.HCHuckleberry";
HCHuckleberry.minCount = 2;
HCHuckleberry.maxCount = 5;
HCHuckleberry.skill = 3;
local HCCranberry = {};
HCCranberry.type = "Hydrocraft.HCCranberry";
HCCranberry.minCount = 2;
HCCranberry.maxCount = 5;
HCCranberry.skill = 3;
local HCSeaberry = {};
HCSeaberry.type = "Hydrocraft.HCSeaberry";
HCSeaberry.minCount = 2;
HCSeaberry.maxCount = 5;
HCSeaberry.skill = 10;
local HCBlackcurrant = {};
HCBlackcurrant.type = "Hydrocraft.HCBlackcurrant";
HCBlackcurrant.minCount = 2;
HCBlackcurrant.maxCount = 5;
HCBlackcurrant.skill = 10;
local HCRedcurrant = {};
HCRedcurrant.type = "Hydrocraft.HCRedcurrant";
HCRedcurrant.minCount = 2;
HCRedcurrant.maxCount = 5;
HCRedcurrant.skill = 10;
local HCArrowwoodberry = {};
HCArrowwoodberry.type = "Hydrocraft.HCArrowwoodberry";
HCArrowwoodberry.minCount = 2;
HCArrowwoodberry.maxCount = 5;
HCArrowwoodberry.skill = 3;
local HCRaspberry = {};
HCRaspberry.type = "Hydrocraft.HCRaspberry";
HCRaspberry.minCount = 2;
HCRaspberry.maxCount = 5;
HCRaspberry.skill = 3;
local HCElderberry = {};
HCElderberry.type = "Hydrocraft.HCElderberry";
HCElderberry.minCount = 2;
HCElderberry.maxCount = 5;
HCElderberry.skill = 2;
local HCHolly = {};
HCHolly.type = "Hydrocraft.HCHolly";
HCHolly.minCount = 2;
HCHolly.maxCount = 5;
HCHolly.skill = 2;
local HCBlackthornberry = {};
HCBlackthornberry.type = "Hydrocraft.HCBlackthornberry";
HCBlackthornberry.minCount = 2;
HCBlackthornberry.maxCount = 5;
HCBlackthornberry.skill = 9;
local HCCrampbarkberry = {};
HCCrampbarkberry.type = "Hydrocraft.HCCrampbarkberry";
HCCrampbarkberry.minCount = 2;
HCCrampbarkberry.maxCount = 5;
HCCrampbarkberry.skill = 10;
local HCCrowberry = {};
HCCrowberry.type = "Hydrocraft.HCCrowberry";
HCCrowberry.minCount = 2;
HCCrowberry.maxCount = 5;
HCCrowberry.skill = 9;
local HCGooseberry = {};
HCGooseberry.type = "Hydrocraft.HCGooseberry";
HCGooseberry.minCount = 2;
HCGooseberry.maxCount = 5;
HCGooseberry.skill = 10;
local HCHawthornfruit = {};
HCHawthornfruit.type = "Hydrocraft.HCHawthornfruit";
HCHawthornfruit.minCount = 2;
HCHawthornfruit.maxCount = 5;
HCHawthornfruit.skill = 9;
local HCJuniperberry = {};
HCJuniperberry.type = "Hydrocraft.HCJuniperberry";
HCJuniperberry.minCount = 2;
HCJuniperberry.maxCount = 5;
HCJuniperberry.skill = 3;
local HCSumacberry = {};
HCSumacberry.type = "Hydrocraft.HCSumacberry";
HCSumacberry.minCount = 2;
HCSumacberry.maxCount = 5;
HCSumacberry.skill = 3;
local HCGrass = {};
HCGrass.type = "Hydrocraft.HCGrass";
HCGrass.minCount = 2;
HCGrass.maxCount = 6;
HCGrass.skill = 0;
local HCReeds = {};
HCReeds.type = "Hydrocraft.HCReeds";
HCReeds.minCount = 2;
HCReeds.maxCount = 6;
HCReeds.skill = 2;
local HCFlax = {};
HCFlax.type = "Hydrocraft.HCFlax";
HCFlax.minCount = 2;
HCFlax.maxCount = 6;
HCFlax.skill = 2;
local HCMilkweedroot = {};
HCMilkweedroot.type = "Hydrocraft.HCMilkweedroot";
HCMilkweedroot.minCount = 2;
HCMilkweedroot.maxCount = 6;
HCMilkweedroot.skill = 3;
local HCClover = {};
HCClover.type = "Hydrocraft.HCClover";
HCClover.minCount = 2;
HCClover.maxCount = 6;
HCClover.skill = 2;
local HCNettles = {};
HCNettles.type = "Hydrocraft.HCNettles";
HCNettles.minCount = 2;
HCNettles.maxCount = 6;
HCNettles.skill = 4;
local HCThistle = {};
HCThistle.type = "Hydrocraft.HCThistle";
HCThistle.minCount = 2;
HCThistle.maxCount = 6;
HCThistle.skill = 4;
local HCJutestems = {};
HCJutestems.type = "Hydrocraft.HCJutestems";
HCJutestems.minCount = 2;
HCJutestems.maxCount = 6;
HCJutestems.skill = 2;
local HCValerian = {};
HCValerian.type = "Hydrocraft.HCValerian";
HCValerian.minCount = 1;
HCValerian.maxCount = 2;
HCValerian.skill = 3;
local HCRosebud = {};
HCRosebud.type = "Hydrocraft.HCRosebud";
HCRosebud.minCount = 1;
HCRosebud.maxCount = 2;
HCRosebud.skill = 3;
local HCSunflower = {};
HCSunflower.type = "Hydrocraft.HCSunflower";
HCSunflower.minCount = 1;
HCSunflower.maxCount = 2;
HCSunflower.skill = 6;
local HCVenusflytrap = {};
HCVenusflytrap.type = "Hydrocraft.HCVenusflytrap";
HCVenusflytrap.minCount = 1;
HCVenusflytrap.maxCount = 2;
HCVenusflytrap.skill = 6;
local HCCamomile = {};
HCCamomile.type = "Hydrocraft.HCCamomile";
HCCamomile.minCount = 1;
HCCamomile.maxCount = 2;
HCCamomile.skill = 3;
local HCLavender = {};
HCLavender.type = "Hydrocraft.HCLavender";
HCLavender.minCount = 1;
HCLavender.maxCount = 2;
HCLavender.skill = 3;
local HCFlaxflower = {};
HCFlaxflower.type = "Hydrocraft.HCFlaxflower";
HCFlaxflower.minCount = 1;
HCFlaxflower.maxCount = 2;
HCFlaxflower.skill = 3;
local HCDaisy = {};
HCDaisy.type = "Hydrocraft.HCDaisy";
HCDaisy.minCount = 1;
HCDaisy.maxCount = 2;
HCDaisy.skill = 3;
local HCIris = {};
HCIris.type = "Hydrocraft.HCIris";
HCIris.minCount = 1;
HCIris.maxCount = 2;
HCIris.skill = 3;
local HCSkullcap = {};
HCSkullcap.type = "Hydrocraft.HCSkullcap";
HCSkullcap.minCount = 1;
HCSkullcap.maxCount = 2;
HCSkullcap.skill = 3;
local HCBluebell = {};
HCBluebell.type = "Hydrocraft.HCBluebell";
HCBluebell.minCount = 1;
HCBluebell.maxCount = 2;
HCBluebell.skill = 3;
local HCStraw = {};
HCStraw.type = "Hydrocraft.HCStraw";
HCStraw.minCount = 2;
HCStraw.maxCount = 6;
HCStraw.skill = 0;
local HCBark = {};
HCBark.type = "Hydrocraft.HCBark";
HCBark.minCount = 1;
HCBark.maxCount = 2;
HCBark.skill = 0;
local HCBirchbark= {};
HCBirchbark.type = "Hydrocraft.HCBirchbark";
HCBirchbark.minCount = 1;
HCBirchbark.maxCount = 2;
HCBirchbark.skill = 0;
local HCWillowbark= {};
HCWillowbark.type = "Hydrocraft.HCWillowbark";
HCWillowbark.minCount = 1;
HCWillowbark.maxCount = 2;
HCWillowbark.skill = 0;
local HCFircone = {};
HCFircone.type = "Hydrocraft.HCFircone";
HCFircone.minCount = 1;
HCFircone.maxCount = 2;
HCFircone.skill = 2;
local HCAcorn = {};
HCAcorn.type = "Hydrocraft.HCAcorn";
HCAcorn.minCount = 1;
HCAcorn.maxCount = 2;
HCAcorn.skill = 2;
local HCBirchcatkin = {};
HCBirchcatkin.type = "Hydrocraft.HCBirchcatkin";
HCBirchcatkin.minCount = 1;
HCBirchcatkin.maxCount = 2;
HCBirchcatkin.skill = 3;
local HCBeechnut = {};
HCBeechnut.type = "Hydrocraft.HCBeechnut";
HCBeechnut.minCount = 1;
HCBeechnut.maxCount = 2;
HCBeechnut.skill = 2;
local HCChestnut = {};
HCChestnut.type = "Hydrocraft.HCChestnut";
HCChestnut.minCount = 1;
HCChestnut.maxCount = 2;
HCChestnut.skill = 2;
local HCHickorynuts = {};
HCHickorynuts.type = "Hydrocraft.HCHickorynuts";
HCHickorynuts.minCount = 1;
HCHickorynuts.maxCount = 2;
HCHickorynuts.skill = 2;
local HCHickoryleaves = {};
HCHickoryleaves.type = "Hydrocraft.HCHickoryleaves";
HCHickoryleaves.minCount = 1;
HCHickoryleaves.maxCount = 2;
HCHickoryleaves.skill = 1;
local HCOakleaves = {};
HCOakleaves.type = "Hydrocraft.HCOakleaves";
HCOakleaves.minCount = 1;
HCOakleaves.maxCount = 2;
HCOakleaves.skill = 1;
local HCMapleleaf = {};
HCMapleleaf.type = "Hydrocraft.HCMapleleaf";
HCMapleleaf.minCount = 2;
HCMapleleaf.maxCount = 4;
HCMapleleaf.skill = 1;
local HCFern = {};
HCFern.type = "Hydrocraft.HCFern";
HCFern.minCount = 2;
HCFern.maxCount = 4;
HCFern.skill = 1;
local HCFiddleheadfern = {};
HCFiddleheadfern.type = "Hydrocraft.HCFiddleheadfern";
HCFiddleheadfern.minCount = 2;
HCFiddleheadfern.maxCount = 4;
HCFiddleheadfern.skill = 1;
local HCWillowbranch = {};
HCWillowbranch.type = "Hydrocraft.HCWillowbranch";
HCWillowbranch.minCount = 1;
HCWillowbranch.maxCount = 2;
HCWillowbranch.skill = 1;
local HCAlderbough = {};
HCAlderbough.type = "Hydrocraft.HCAlderbough";
HCAlderbough.minCount = 1;
HCAlderbough.maxCount = 2;
HCAlderbough.skill = 1;
local HCElmbough = {};
HCElmbough.type = "Hydrocraft.HCElmbough";
HCElmbough.minCount = 1;
HCElmbough.maxCount = 2;
HCElmbough.skill = 1;
local HCSprucebough = {};
HCSprucebough.type = "Hydrocraft.HCSprucebough";
HCSprucebough.minCount = 1;
HCSprucebough.maxCount = 2;
HCSprucebough.skill = 1;
local HCYewbough = {};
HCYewbough.type = "Hydrocraft.HCYewbough";
HCYewbough.minCount = 1;
HCYewbough.maxCount = 2;
HCYewbough.skill = 1;
local HCPinebough = {};
HCPinebough.type = "Hydrocraft.HCPinebough";
HCPinebough.minCount = 1;
HCPinebough.maxCount = 2;
HCPinebough.skill = 1;
local HCFirbough = {};
HCFirbough.type = "Hydrocraft.HCFirbough";
HCFirbough.minCount = 1;
HCFirbough.maxCount = 2;
HCFirbough.skill = 1;
local HCCrabapple = {};
HCCrabapple.type = "Hydrocraft.HCCrabapple";
HCCrabapple.minCount = 1;
HCCrabapple.maxCount = 1;
HCCrabapple.skill = 10;
local HCCabbage = {};
HCCabbage.type = "farming.Cabbage";
HCCabbage.minCount = 1;
HCCabbage.maxCount = 1;
HCCabbage.skill = 8;
local HCWildcarrot = {};
HCWildcarrot.type = "Base.HCWildcarrot";
HCWildcarrot.minCount = 1;
HCWildcarrot.maxCount = 1;
HCWildcarrot.skill = 8;
local HCCorn = {};
HCCorn.type = "Base.Corn";
HCCorn.minCount = 1;
HCCorn.maxCount = 1;
HCCorn.skill = 9;
local HCGrapes = {};
HCGrapes.type = "Base.Grapes";
HCGrapes.minCount = 1;
HCGrapes.maxCount = 1;
HCGrapes.skill = 10;
local HCLemon = {};
HCLemon.type = "Base.Lemon";
HCLemon.minCount = 1;
HCLemon.maxCount = 1;
HCLemon.skill = 10;
local HCOrange = {};
HCOrange.type = "Base.Orange";
HCOrange.minCount = 1;
HCOrange.maxCount = 1;
HCOrange.skill = 10;
local HCPotato = {};
HCPotato.type = "farming.Potato";
HCPotato.minCount = 1;
HCPotato.maxCount = 1;
HCPotato.skill = 8;
local HCRedRadish = {};
HCRedRadish.type = "Base.RedRadish";
HCRedRadish.minCount = 1;
HCRedRadish.maxCount = 1;
HCRedRadish.skill = 8;
local HCTomato = {};
HCTomato.type = "farming.Tomato";
HCTomato.minCount = 1;
HCTomato.maxCount = 1;
HCTomato.skill = 9;
local HCMulberryleaf = {};
HCMulberryleaf.type = "Hydrocraft.HCMulberryleaf";
HCMulberryleaf.minCount = 1;
HCMulberryleaf.maxCount = 2;
HCMulberryleaf.skill = 3;
local HCMulberry = {};
HCMulberry.type = "Hydrocraft.HCMulberry";
HCMulberry.minCount = 2;
HCMulberry.maxCount = 5;
HCMulberry.skill = 3;
local HCBlewitshroom = {};
HCBlewitshroom.type = "Hydrocraft.HCBlewitshroom";
HCBlewitshroom.minCount = 1;
HCBlewitshroom.maxCount = 2;
HCBlewitshroom.skill = 5;
local HCLobstershroom = {};
HCLobstershroom.type = "Hydrocraft.HCLobstershroom";
HCLobstershroom.minCount = 1;
HCLobstershroom.maxCount = 2;
HCLobstershroom.skill = 7;
local HCWitchshatshroom = {};
HCWitchshatshroom.type = "Hydrocraft.HCWitchshatshroom";
HCWitchshatshroom.minCount = 1;
HCWitchshatshroom.maxCount = 2;
HCWitchshatshroom.skill = 7;
local HCYellowmorelshroom = {};
HCYellowmorelshroom.type = "Hydrocraft.HCYellowmorelshroom";
HCYellowmorelshroom.minCount = 1;
HCYellowmorelshroom.maxCount = 2;
HCYellowmorelshroom.skill = 7;
local HCChantrelle = {};
HCChantrelle.type = "Hydrocraft.HCChantrelle";
HCChantrelle.minCount = 1;
HCChantrelle.maxCount = 2;
HCChantrelle.skill = 4;

table.insert(scavenges.berries, HCCandleberry);
table.insert(scavenges.berries, HCHuckleberry);
table.insert(scavenges.berries, HCCranberry);
table.insert(scavenges.berries, HCSeaberry);
table.insert(scavenges.berries, HCBlackcurrant);
table.insert(scavenges.berries, HCRedcurrant);
table.insert(scavenges.berries, HCArrowwoodberry);
table.insert(scavenges.berries, HCRaspberry);
table.insert(scavenges.berries, HCElderberry);
table.insert(scavenges.berries, HCHolly);
table.insert(scavenges.berries, HCBlackthornberry);
table.insert(scavenges.berries, HCCrampbarkberry);
table.insert(scavenges.berries, HCCrowberry);
table.insert(scavenges.berries, HCGooseberry);
table.insert(scavenges.berries, HCHawthornfruit);
table.insert(scavenges.berries, HCJuniperberry);
table.insert(scavenges.berries, HCSumacberry);
table.insert(scavenges.forestGoods, HCGrass);
table.insert(scavenges.forestGoods, HCReeds);
table.insert(scavenges.forestGoods, HCFlax);
table.insert(scavenges.forestGoods, HCMilkweedroot);
table.insert(scavenges.forestGoods, HCClover);
table.insert(scavenges.forestGoods, HCNettles);
table.insert(scavenges.forestGoods, HCThistle);
table.insert(scavenges.forestGoods, HCJutestems);
table.insert(scavenges.forestGoods, HCValerian);
table.insert(scavenges.forestGoods, HCRosebud);
table.insert(scavenges.forestGoods, HCSunflower);
table.insert(scavenges.forestGoods, HCVenusflytrap);
table.insert(scavenges.forestGoods, HCCamomile);
table.insert(scavenges.forestGoods, HCLavender);
table.insert(scavenges.forestGoods, HCFlaxflower);
table.insert(scavenges.forestGoods, HCDaisy);
table.insert(scavenges.forestGoods, HCIris);
table.insert(scavenges.forestGoods, HCSkullcap);
table.insert(scavenges.forestGoods, HCBluebell);
table.insert(scavenges.forestGoods, HCStraw);
table.insert(scavenges.forestGoods, HCBark);
table.insert(scavenges.forestGoods, HCBirchbark);
table.insert(scavenges.forestGoods, HCWillowbark);
table.insert(scavenges.forestGoods, HCFircone);
table.insert(scavenges.forestGoods, HCAcorn);
table.insert(scavenges.forestGoods, HCBirchcatkin);
table.insert(scavenges.forestGoods, HCBeechnut);
table.insert(scavenges.forestGoods, HCChestnut);
table.insert(scavenges.forestGoods, HCHickorynuts);
table.insert(scavenges.forestGoods, HCHickoryleaves);
table.insert(scavenges.forestGoods, HCOakleaves);
table.insert(scavenges.forestGoods, HCMapleleaf);
table.insert(scavenges.forestGoods, HCFern);
table.insert(scavenges.forestGoods, HCFiddleheadfern);
table.insert(scavenges.forestGoods, HCWillowbranch);
table.insert(scavenges.forestGoods, HCAlderbough);
table.insert(scavenges.forestGoods, HCElmbough);
table.insert(scavenges.forestGoods, HCSprucebough);
table.insert(scavenges.forestGoods, HCYewbough);
table.insert(scavenges.forestGoods, HCPinebough);
table.insert(scavenges.forestGoods, HCFirbough);
table.insert(scavenges.berries, HCCrabapple);
table.insert(scavenges.berries, HCCabbage);
table.insert(scavenges.berries, HCWildcarrot);
table.insert(scavenges.berries, HCGrapes);
table.insert(scavenges.berries, HCLemon);
table.insert(scavenges.berries, HCOrange);
table.insert(scavenges.berries, HCPotato);
table.insert(scavenges.berries, HCRedRadish);
table.insert(scavenges.berries, HCTomato);
table.insert(scavenges.berries, HCMulberry);
table.insert(scavenges.forestGoods, HCMulberryleaf);
table.insert(scavenges.mushrooms, HCBlewitshroom);
table.insert(scavenges.mushrooms, HCLobstershroom);
table.insert(scavenges.mushrooms, HCWitchshatshroom);
table.insert(scavenges.mushrooms, HCYellowmorelshroom);
table.insert(scavenges.mushrooms, HCChantrelle);
